### PR TITLE
Fix typo in conext/set_default_oc_path docstring

### PR DESCRIPTION
**Pull request by tonejito**
Fixed a typo in the docstring for function `set_default_oc_path` in the `packages/openshift/context.py` file.

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@tonejito Please run `./ansible/rebuild_module.sh` and include any additional files to your PR.
Thanks!

**Comment by tonejito** [comment]
@bradmwilliams I updated the digests produced by `./ansible/rebuild_module.sh`

**Review by bradmwilliams — APPROVED** [review]

**Comment by bradmwilliams** [comment]
@tonejito Thanks for your contribution! 
Sorry for all the noise over the past few days!

**Pull request merged**
