### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by michaeltcoelho**
Make this library installable.

### CODE REVIEW

**Comment by bradmwilliams** [comment]
Hey @michaeltcoelho 
Just a reminder....
You'll need to run 'ansible/rebuild_module.sh' and include changes in this PR.

**Comment by michaeltcoelho** [comment]
@bradmwilliams WDYT?

**Comment by michaeltcoelho** [comment]
just did that!

**Comment by bradmwilliams** [comment]
You'll have to do it again.  The SHA that is being calculated is different than the version that you committed.

**Comment by michaeltcoelho** [comment]
Done!

**Comment by michaeltcoelho** [comment]
@bradmwilliams LGTM?

**Comment by bradmwilliams** [comment]
> @bradmwilliams LGTM?
Your change do look good.  However, you updated your PR while I was mid-flight making similar changes myself.  My changes have all been committed and merged, so the majority of your PR shouldn't be necessary any longer.  I did omit your pipenv file changes, if you want to include them.  Also, the util.py change, that you proposed, is no longer necessary since PR #55 was merged.

Sorry for any inconvenience!

**Pull request closed without merging**
