### PR TITLE
Sending the process output to the APIObject as a string

### PR DESCRIPTION
**Pull request by psolarvi**
The `process` output is a string, so we need to pass it in the correct constructor parameter. Otherwise the construction of the object is going to fail because it thinks that the parameter we are sending is a dict.

**Output of the issue**
```
Traceback (most recent call last):
  File "./demo.py", line 27, in <module>
    yeah.deploy_template()
  File "./demo.py", line 21, in deploy_template
    processed_template = template.process(cmd_args=['-n', self.PROJECT])
  File "packages/openshift/apiobject.py", line 719, in process
    return APIObject(r.out()).elements()
  File "packages/openshift/apiobject.py", line 99, in __init__
    self.model = Model(dict_to_model)
  File "packages/openshift/model.py", line 243, in __init__
    for k, v in dict_to_model.items():
AttributeError: 'str' object has no attribute 'items'
```

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@psolarvi This PR failed with the following error:
`You need to run ansible/rebuild_module.sh and include changes in this PR`

Also, if possible, can you attach the code, or a link to a gist, that is producing the error above?

**Comment by bradmwilliams** [comment]
@psolarvi I was able to verify this with an example, that I will add to the repository, in a separate PR.  This was a good find!  Thank you!  Please update your PR and I will merge it.

**Comment by bradmwilliams** [comment]
I have added an example (examples/templates.py) that illustrates this problem.  Once this PR merges, the script should work without issue.

**Comment by psolarvi** [comment]
**Script used to test the issue**
(Is not 100% the same of the original in which I found the issue but I picked the required parts to be able to replicate the issue)
```python
#!/usr/bin/env python3

from openshift import APIObject


class TestOcp:
    TEMPLATE_PATH = 'path/to/news-template.yaml'
    PROJECT = 'my-project'

    def deploy_template(self) -> None:
        with open(self.TEMPLATE_PATH) as templateFile:
            template = APIObject(None, templateFile.read())

        processed_template = template.process(cmd_args=['-n', self.PROJECT])


t = TestOcp()
t.deploy_template()

```
**Template file**
```yaml
apiVersion: v1
kind: Template
metadata:
  name: news-feed
  annotations:
    description: "News feed sample application"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: news-ok
    spec:
      selector:
        matchLabels:
          app: news
      replicas: 1
      template:
        metadata:
          labels:
            app: news
        spec:
          containers:
            - name: news
              image: quay.io/redhattraining/ossm-python-flask-gossip:2.0
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
  - kind: Service
    apiVersion: v1
    metadata:
      name: news
    spec:
      ports:
        - port: 5000
          protocol: TCP
          targetPort: 5000
      selector:
        app: news
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: news
    spec:
      to:
        kind: Service
        name: news
      port:
        targetPort: 5000
parameters:
  - name: DATA_FOLDER
    description: "Folder that stores the news"
    required: false
    value: ""
  - name: ERROR_RESPONSE
    description: "Error response on issues finding the news file"
    required: false
    value: ""

```

**Pull request merged**
